project-copacetic/copacetic

CONTRIBUTING.md
Update contribution guidelines to describe use of Developer Certificate of Origin (DCO) instead of a Contributor Licensing Agreement (CLA).
=> docs: replace CLA requirement with DCO

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml
* Remove security policy link in issues config.yml as the new github private vulnerability reporting feature makes it redundant.
* Fix link to security policy in bug_report.yml issue template.
Signed-off-by: Simon Leet <simon.leet@microsoft.com>
=> docs: update issue templates

website/docusaurus.config.js
Signed-off-by: Xander Grzywinski <xgrzywinski@microsoft.com>
Add anonymized analytics to the docs site. This does not track any user information, just gives us an idea of which sections of the docs are drawing the most traffic
=> add anonymized analytics to docs site

README.md
Fix casing for link to code of conduct used by Contributor Covenant badge in README.md
Signed-off-by: Simon Leet <simon.leet@microsoft.com>
=> docs: fix Contributor Covenant badge in README

.github/workflows/build.yml
Lockdown of `GITHUB_TOKEN` permissions revealed that the test jobs were attempting to rebuild and push the devcontainer and failing. This change corrects the `test-patch` job in build.yaml to use the cached devcontainer from the `build` step and not attempt to push it again when the job completes.
Signed-off-by: Simon Leet <simon.leet@microsoft.com>
=> ci: use cached devcontainer in test jobs

.github/workflows/codeql.yml
Enable GitHub CodeQL scanning for this repo.
Signed-off-by: Simon Leet <simon.leet@microsoft.com>
=> ci: add codeql scanning

.github/workflows/test-images.json, pkg/pkgmgr/dpkg.go, pkg/pkgmgr/pkgmgr.go, pkg/pkgmgr/rpm.go
- Match naming of libssl1.1 status.d control file to match libssl1 as provided by the distroless base image. This implementation truncates all package file names to the first period, which does not affect other existing packages in the base images seen in the distroless images test set, but may need to be revisited if that behavior changes.
- Add test case for distroless libssl1.1 patching.
- Fix failure to copy unpacked update files to target image if the tooling image already has the latest versions of the files. dpkg.go now unpacks the update files to a separate root and copies those into a layer for merge into the target image instead of relying of a diff layer after unpacking the update files into the tooling image.
- Clarify in comments for rpm.go why the distroless patching …
=> fix: google distroless patching for libssl1.1

.github/workflows/test-images.json, pkg/pkgmgr/apk.go
Add apk packages before upgrading. This works around the issue where packages require other packages in the dependency tree to be updated.
=> fix: add apk add

CODEOWNERS
Remove @CodeMonkeyLeet from CODEOWNERS file as an emeritus maintainer.
Closes #61
=> ci: remove @codemonkeyleet from codeowners

.github/workflows/test-images.json
Remove grafana image renderer test to unblock the CI
This image is using alpine `edge` repo so it is not suitable for this: https://github.com/grafana/grafana-image-renderer/blob/master/Dockerfile#L9-L11
=> test: remove grafana image renderer test

pkg/pkgmgr/apk.go, pkg/pkgmgr/dpkg.go, pkg/pkgmgr/rpm.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Add http proxy support when executing package managers.
Closes #80
=> feat: add http proxy support when executing package managers

.github/workflows/test-images.json, pkg/pkgmgr/pkgmgr.go, pkg/pkgmgr/rpm.go
=> feat: add centos and amazon linux support

main.go
The makefile specifies main.version in the ldflags.  This PR just pulls that value into the Version property of the command, lighting up `--version`.
Closes #158
=> feat: add version flag

.goreleaser.yml
Publish Darwin/arm64 binaries as Copa is supported on mac os when buildkitd is running as a container. 
Closes #104
=> feat: publish Darwin binaries in release

website/docs/quick-start.md
=> docs: Update docs for new connection methods

.github/workflows/build.yml, go.mod, go.sum, integration/patch_test.go, pkg/patch/cmd.go, pkg/patch/patch.go, pkg/pkgmgr/apk.go, pkg/pkgmgr/apk_test.go, pkg/pkgmgr/dpkg.go, pkg/pkgmgr/dpkg_test.go, pkg/pkgmgr/pkgmgr.go, pkg/pkgmgr/rpm.go, pkg/pkgmgr/rpm_test.go, pkg/report/qualys.go, pkg/report/report_test.go, pkg/report/trivy.go, pkg/types/types.go, pkg/vex/openvex.go, pkg/vex/openvex_test.go, pkg/vex/vex.go, pkg/vex/vex_test.go, website/docs/output.md, website/sidebars.js
Signed-off-by: Sertac Ozercan <sozercan@gmail.com>
Add support for VEX output
Closes #87
example output (`nginx:1.21.6`): https://snips.sh/f/JReDjyIUmp
=> feat: vex output

pkg/pkgmgr/rpm.go
handle mariner zstd compression as `busybox rpm` does not support zstd compression
> Switch rpm package building to use to zstd compression level 7
https://github.com/microsoft/CBL-Mariner/releases/tag/2.0.20230805-2.0
this should fix the broken e2e
=> fix: handle mariner zstd compression

pkg/pkgmgr/rpm.go
=> chore: cherry pick #295 into 0.4

website/docs/quick-start.md
Fixed a typo in supported formats list.
=> docs: Fix typo in quick-start.md

pkg/pkgmgr/dpkg.go
"apt update" should never be cached.
This also shouldn't break caching for anything run after it unless the
rootfs changed (ie. apt cache was actually updated).
=> fix: ignore cache for "apt update"

pkg/pkgmgr/rpm.go
Moving to `yumdownloader` since Mariner repo seems to be having issues with certain packages (like `glibc-iconv`) being downloaded via `yum reinstall --downloadonly ...`
Closes #376
=> fix: migrate to yumdownloader

.github/workflows/build.yml, .github/workflows/golangci-lint.yml, Makefile, main.go, pkg/buildkit/buildkit.go, pkg/patch/cmd.go, pkg/patch/cmd_test.go, pkg/patch/patch.go, pkg/patch/patch_test.go, pkg/pkgmgr/apk.go, pkg/pkgmgr/apk_test.go, pkg/pkgmgr/dpkg.go, pkg/pkgmgr/dpkg_test.go, pkg/pkgmgr/pkgmgr.go, pkg/pkgmgr/pkgmgr_test.go, pkg/pkgmgr/rpm.go, pkg/pkgmgr/rpm_test.go, pkg/report/report.go, pkg/report/report_test.go, pkg/report/trivy.go, pkg/report/trivy_test.go, pkg/test_utils/utils.go, pkg/test_utils/utils_test.go, pkg/types/types.go, pkg/utils/log.go, pkg/utils/log_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Remove old MIT license headers and replace with Apache 2
Closes #351
=> docs: update MIT license headers to Apache 2

.github/workflows/scripts/buildkitenvs/docker/custom-unix, go.mod, go.sum, integration/fixtures/test-images.json, integration/patch_test.go, pkg/buildkit/buildkit.go, pkg/buildkit/buildkit_test.go, pkg/patch/patch.go, pkg/pkgmgr/apk.go, pkg/pkgmgr/apk_test.go, pkg/pkgmgr/dpkg.go, pkg/pkgmgr/dpkg_test.go, pkg/pkgmgr/pkgmgr.go, pkg/pkgmgr/rpm.go, pkg/pkgmgr/rpm_test.go, website/docs/quick-start.md
Use gateway client for config resolution
Implement `buildkit.ExtractFileFromState`
This code will still not compile, since the signature of `buildkit.SolveToLocal` is not satisfied by its calls.
Replace `SolveToLocal` in `probeDPKGStatus` method
In this case, we will write the status type to a file, which we thereafter read from the state as a single byte.
Fix error in awk script
Use `ExtractFileFromState` for dpkg `installUpdates`
Use `ExtractFileFromState` in `unpackAndMergeUpdates`
APK: Use `ExtractFileFromState` for `upgradePackages`
Do not use `SolveToLocal`.
Use `ExtractFileFromState` for `probeRPMStatus`
Replace `buildkit.SolveToLocal` in rpm.go
Update `patchWithContext` to pass the correct client
Fix errors and achieve parity with `main` branch
Update unit tests
Closes #177
=> feat: Prefer local image

pkg/report/trivy.go, pkg/report/trivy_test.go
=> chore: use trivy code

pkg/patch/patch.go
Passing invalid patched image tag causes copa to freeze. This fix validates the patched image tag.
Closes #490
=> fix: validate patched image tag

.github/workflows/build.yml, integration/fixtures/trivy_ignore.rego, integration/patch_test.go
=> ci: ignore CVE-2024-0567 and CVE-2023-5981 to fix ci

pkg/pkgmgr/pkgmgr.go, pkg/pkgmgr/pkgmgr_test.go
=> feat: ignore unpatchable packages and add GetUniqueLatestUpdates test

.github/workflows/build.yml, .github/workflows/check-deps.yml, .github/workflows/codeql.yml, .github/workflows/dependency-review.yml, .github/workflows/golangci-lint.yml, .github/workflows/release.yml
=> ci: bump to go 1.22

website/versioned_docs/version-v0.1.x/introduction.md, website/versioned_docs/version-v0.2.x/introduction.md, website/versioned_docs/version-v0.3.x/introduction.md, website/versioned_docs/version-v0.4.x/introduction.md, website/versioned_docs/version-v0.5.x/introduction.md, website/versioned_docs/version-v0.6.x/introduction.md
Duplicate of https://github.com/project-copacetic/copacetic/pull/572 with the same changes being applied to versioned_docs as well.
Apologies for closing #578, I forgot to make a separate branch while making additional changes. I've made some changes to my workflow in an attempt to make sure this doesn't happen again.
Part of https://github.com/project-copacetic/copacetic/pull/572 and https://github.com/project-copacetic/copacetic/issues/390
=> docs: add mention of support for containers without package managers to versioned_docs

.github/workflows/build.yml, .github/workflows/check-deps.yml, .github/workflows/codeql.yml, .github/workflows/dependency-review.yml, .github/workflows/deploy-docs.yaml
If a ci runs is miscategorized, there are other ci runs that should be classified, or there are any other changes required before merging this PR please let me know so the necessary changes can be made. 
Closes #573
=> ci: add prefix to ci runs

.github/workflows/golangci-lint.yml
Forgot to prefix golangci-lint in #580
=> ci: mark golangci-lint as blocking

website/docs/faq.md
If this change needs to be added to versioned docs, please let me know.
Closes #473
=> docs: add source policy docs for debian 12

website/docs/custom-address.md
Based on the docs I've been able to find about this feature, this documentation should be accurate.
Closes #395
=> docs: add buildkit mtls-over-tcp docs

.github/workflows/scripts/buildkitenvs/docker/custom-unix, integration/patch_test.go
Upgrade dind image to docker:26.1.1-dind and add wait for dind container to status Running.
Closes #609
=> fix: flakey custom unix test

pkg/patch/patch.go
* added more context to the error message found while patching with wrong image reference
Closes #396
=> fix: added context to error

pkg/pkgmgr/rpm.go, pkg/pkgmgr/rpm_test.go
=> feat: add rpm package verification

Makefile
Allow `BINS_OUT_DIR` in Makefile to be configured during call.
=> feat: allow change to BINS_OUT_DIR in makefile

Makefile
Create-docs-pr is failing due to node_version (https://github.com/project-copacetic/copacetic/actions/runs/9811951922/job/27095086641). Upgrades version from 16-bullseye-slim to 20-bullseye-slim.
=> fix: update NODE_VERSION

integration/fixtures/test-images.json, pkg/pkgmgr/rpm.go
Microdnf was missing `-y` and was not updating correctly. 
Closes #714
=> fix: microdnf update

website/docs/introduction.md
After investigation, the Copa team has determined that Wolfi support will not be added at this time due to the complexities required to support this image type.
Closes #596 #38
=> docs: clarify copa does not support wolfi-based images

pkg/patch/patch.go, pkg/pkgmgr/apk.go, pkg/pkgmgr/dpkg.go, pkg/pkgmgr/rpm.go
=> docs: remove outdated todo comments

CONTRIBUTING.md
Adds an additional way to signoff commits within `CONTRIBUTING.md`
=> docs: Add additional way to signoff commits

website/docs/faq.md, website/versioned_docs/version-v0.1.x/faq.md, website/versioned_docs/version-v0.2.x/faq.md, website/versioned_docs/version-v0.3.x/faq.md, website/versioned_docs/version-v0.4.x/faq.md, website/versioned_docs/version-v0.5.x/faq.md, website/versioned_docs/version-v0.6.x/faq.md, website/versioned_docs/version-v0.7.x/faq.md, website/versioned_docs/version-v0.8.x/faq.md
=> docs: Add doc for scanners that report individual layers

website/docs/scanner-plugins.md, website/versioned_docs/version-v0.5.x/scanner-plugins.md, website/versioned_docs/version-v0.6.x/scanner-plugins.md, website/versioned_docs/version-v0.7.x/scanner-plugins.md, website/versioned_docs/version-v0.8.x/scanner-plugins.md, website/versioned_docs/version-v0.9.x/scanner-plugins.md
Removed the trailing comma in the json output example. Copa will error with `Error: error parsing scanner output: invalid character '}' looking for beginning of object key string` with the comma present.
=> docs: fix trailing comma in json

.github/workflows/mirror-tooling-images.yml
Adds workflow that will mirror tooling images to ghcr
Changes the tooling image references to ghcr
Closes #937
for the cache pulling: https://github.com/robert-cronin/copacetic/actions/runs/13689645432/job/38280415279
=> feat: mirror tooling images to ghcr

.github/workflows/golangci-lint.yml, .golangci.yml
Upgrades golangci-lint version in workflow to v2.0.2
Migrates golangci-lint config to version v2 (migration guide can be found here: https://golangci-lint.run/product/migration-guide/)
Closes #993
=> fix: golangci-lint v1 is not supported by golangci-lint-action v7

website/docs/faq.md, website/versioned_docs/version-v0.10.x/faq.md
Add documentation to the websites FAQ page explaining that copa will not be able to patch images that are EOL and OS vendors have taken down the package repositories.
Closes #705
=> docs: explain EOL image error messages in FAQ

integration/fixtures/trivy_ignore.rego
Adds the newly reported shadow-utils CVEs to the ignore list for integration tests. This should unblock main, but we should still investigate why it is occurring. My guess is that dpkg pkgmgr is not able to resolve the fixed package for some reason
=> fix: ignore shadow cves for integration test

pkg/pkgmgr/dpkg.go, pkg/pkgmgr/dpkg_test.go, pkg/pkgmgr/pkgmgr.go, pkg/pkgmgr/rpm.go
Adds fallback mechanisms to the apk and apt based package managers
Closes #980
Should be merged after #978
=> fix: apt apk images fail tooling images missing

pkg/patch/patch.go, pkg/patch/patch_test.go
Add nil pointer dereference guard to buildkit solve response
Add regression test
Closes #1036
=> fix: guard against error buildkit solve

integration/patch_test.go, pkg/patch/patch.go, pkg/utils/mediatype.go, pkg/utils/mediatype_test.go
Adds `getExporterType` to map media type to exporter type directly via a resolution of the descriptor using oras
Closes #842
=> fix: oci media type should be respected

pkg/buildkit/connhelpers/buildx.go, pkg/buildkit/connhelpers/docker.go, pkg/patch/patch.go
1. Get the docker addr from "docker context ls" when `DOCKER_HOST` is not set
2. Fix issue when buildx metadata specifies a docker context name rather than a docker connection string
3. Add support for `buildx dial-stdio` which will proxy connections to buildkit for us rather than manually setting up the connection.
This makes it so `copa` works with Docker Desktop out of the box (no extra settings need to be changed).
It also removes the limitation on the type of buildx instances it can connect to when the installed buildx supports the "dial-stdio" command (which has been around for awhile now).
Closes #543
=> chore: Fix some issues with docker and buildx connections

pkg/buildkit/buildkit.go, pkg/buildkit/buildkit_test.go, pkg/patch/patch.go, pkg/patch/patch_test.go, pkg/types/types.go, pkg/utils/utils.go
- added QemuAvailable() + mapGoArch() helpers to detect binfmt/qemu support for cross-arch builds.
- new helpers for multiarch work:
- archDigest, archTag(), dockerImageDigest(), createManifestCLI() and normalizeConfigForPlatform()
- split the monolithic patchWithContext() into:
- patchSingleArchImage() - one arch at a time (returns *types.PatchResult).
- patchMultiArchImage() - fan-out, run builds in parallel, then stitch a manifest list.
- added new types:
- PatchPlatform: OCI platform + report path
- PatchResult: original image, patched ref, digest
- added argument validation: can't pass both report-file and report-dir
Closes #988
=> feat: add multi arch command changes

pkg/buildkit/buildkit.go, pkg/patch/patch.go, pkg/patch/patch_test.go, pkg/types/types.go
Added table summary for Multi-Arch Patching with Platform, Status, Ref, Error as fields. Wanted feedback on how can I test this code. I'm confused on how to simulate multi-arch patching locally using docker and trivy to test the credibility and making sure the logs are as expected.
Please review the code and let me know this is how we wanted the logs to look. Thanks!
closes: #992
=> feat: Add Multi Arch Enhancements

pkg/patch/patch.go, pkg/patch/patch_test.go, pkg/types/types.go, test/e2e/multiplatform-plugin/multiplatform_plugin_test.go, website/docs/multiplatform-patching.md, website/docusaurus.config.js, website/sidebars.js
Add notes to multiplatform documentation explaining:
- Unpatched platforms are passed through unchanged
- Build attestations and referrers are not preserved
And change multiarch to multiplatform in various places to be consistent
=> docs: improve multiplatform docs

integration/multiarch/fixtures/test-images.json, integration/multiarch/patch_test.go, pkg/patch/patch.go, pkg/utils/utils.go
Retain multiplatform manifest list annotations
Add annotation verification to multiplatform integration tests
Closes #1119
Example of patched image now with annotations retained: https://oci.dag.dev/?image=ghcr.io%2Frobert-cronin%2Fnginx%3A1.27.0-patched-annotations
=> fix: retain multiplatform manifest list annotations

.github/workflows/stale.yml
Added `good first issue` in the exempted issue labels for the stale bot.
=> chore: Exempt good first issues from getting stale

website/docs/multiplatform-patching.md, website/versioned_docs/version-v0.11.x/multiplatform-patching.md
This PR adds the `--image-src` flag to the trivy command snippet in the multi-platform docs. Without this flag, trivy puts the incorrect arch in the report causing cop to skip platforms that are expected to be patched.
Closes #1281
=> docs: add --image-src to trivy

integration/common/fixtures/trivy_ignore.rego, integration/singlearch/fixtures/test-images.json
Ignores CVE-2025-3576 until krb5 `1.19.4-4` is available.
Closes #1303
=> chore: remove ignore errors for cbl mariner imgs and ignore CVE-2025-3576
