project-copacetic/copacetic

.github/workflows/build.yml, Makefile, codecov.yml, pkg/utils/log_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
* Add unit tests for pkg/utils
* Add codecov to build.yml pipeline
=> ci: add codecov support

.github/semantic.yml
Add semantic.yml to define accepted Semantic Commits types to enforce. See https://github.com/Ezard/semantic-prs.
=> ci: define semantic types and title only

.github/workflows/test-images.json, pkg/pkgmgr/apk.go, pkg/pkgmgr/dpkg.go, pkg/pkgmgr/pkgmgr.go, pkg/pkgmgr/rpm.go
cherry pick #41 #44 #60 to release 0.1
=> fix: cherry pick #41 #44 #60

.goreleaser.yml
=> fix: add version to release archive

.github/workflows/build.yml, README.md
=> docs: add openssf badge

.goreleaser.yml
=> build: fix release version

website/package.json, website/yarn.lock
This is causing some issues deploying docs, downgrading for now
=> chore: downgrade mdx-js/react

.github/workflows/check-deps.yml, .github/workflows/golangci-lint.yml, .github/workflows/release.yml
=> chore: bump to go 1.21

website/docs/faq.md, website/sidebars.js, website/versioned_docs/version-v0.1.x/faq.md, website/versioned_docs/version-v0.2.x/faq.md, website/versioned_docs/version-v0.3.x/faq.md, website/versioned_docs/version-v0.4.x/faq.md, website/versioned_sidebars/version-v0.1.x-sidebars.json, website/versioned_sidebars/version-v0.2.x-sidebars.json, website/versioned_sidebars/version-v0.3.x-sidebars.json, website/versioned_sidebars/version-v0.4.x-sidebars.json
=> docs: add faq section to docs

README.md, website/docs/contributing.md, website/versioned_docs/version-v0.3.x/contributing.md, website/versioned_docs/version-v0.4.x/contributing.md
=> docs: add slack and meeting info

.github/workflows/release.yml
Signed-off-by: ashnamehrotra <ashnamehrotra@gmail.com>
=> fix: add package permissions

.github/workflows/release.yml
Cherry pick #317 into release-0.4
=> chore: cherry pick #317 into release-0.4

README.md
add fossa badge for CNCF onboarding
=> docs: add fossa badge

website/sidebars.js
Signed-off-by: ashnamehrotra <ashnamehrotra@gmail.com>
Closes #337
=> fix: add release and github action pages to sidebar

.github/dependabot.yml
=> ci: add gha and npm groups

website/versioned_docs/version-v0.1.x/faq.md, website/versioned_docs/version-v0.2.x/faq.md, website/versioned_docs/version-v0.3.x/faq.md, website/versioned_docs/version-v0.4.x/faq.md
=> docs: update versioned docs faq

.github/workflows/release.yml
=> fix: cherry pick #393

.github/workflows/build.yml, .github/workflows/check-deps.yml, .github/workflows/dependency-review.yml, .github/workflows/golangci-lint.yml, .github/workflows/release.yml
=> ci: fix go version in govulncheck

website/docs/quick-start.md, website/versioned_docs/version-v0.6.x/quick-start.md
=> docs: fix docs issues

website/docs/custom-address.md, website/docs/installation.md, website/docs/quick-start.md, website/sidebars.js, website/versioned_docs/version-v0.6.x/custom-address.md, website/versioned_docs/version-v0.6.x/installation.md, website/versioned_docs/version-v0.6.x/quick-start.md, website/versioned_sidebars/version-v0.6.x-sidebars.json
Quick start contains too much information, splitting custom addresses into a seperate page
=> docs: revamp quick start

website/versioned_docs/version-v0.6.x/best-practices.md
Quick update to cover the miss from the last PR
=> docs: update missed tagging guidelines page

integration/fixtures/test-images.json
Replaces EOL Mariner 1.0 images with 2.0
Closes #523
=> test: replace mariner 1.0 test images

website/docs/introduction.md
First commit to the repo so feedback is welcomed. If there is any additional information required or a better place to put this in the docs, please let me know so I can make the necessary changes. 
Closes #390
=> docs: add mention of support for containers without package managers

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/request.yml, README.md, website/docs/contributing.md, website/versioned_docs/version-v0.3.x/contributing.md, website/versioned_docs/version-v0.4.x/contributing.md, website/versioned_docs/version-v0.5.x/contributing.md, website/versioned_docs/version-v0.6.x/contributing.md
=> docs: update slack to cncf

integration/fixtures/test-images-non-distroless.json, integration/fixtures/test-images.json, pkg/patch/patch.go, pkg/patch/patch_test.go, pkg/pkgmgr/pkgmgr.go
=> feat: add rocky linux support

website/docs/quick-start.md
=> docs: patching with digest

ADOPTERS.md
Add Helmper to ADOPTERS.md
Closes #639
=> docs: added helmper to adopters list

website/docs/development-tips.md
Add code in documentation for function to be included in buildkit to allow the usage of buildkit.SolveToDocker function in development tips
Closes #671
=> docs: add function to be included when using buildkit.SolveToDocker

.github/workflows/deploy-docs.yaml
This is a blocking test since it will affect future doc generation
=> ci: classify gen docs as blocking

.github/workflows/build.yml
=> ci: bump trivy and buildkit version for test

pkg/pkgmgr/dpkg.go
- Adds logging of held packages
Closes #496
=> feat: log for held packages

pkg/patch/patch.go
=> fix: warn if output file specified without vuln report

website/docs/docker-extension.md, website/sidebars.js
=> docs: add docker extension

pkg/pkgmgr/dpkg.go, pkg/pkgmgr/dpkg_test.go, pkg/pkgmgr/pkgmgr.go, pkg/pkgmgr/rpm.go, pkg/pkgmgr/rpm_test.go
Changes the tooling image references to ghcr
Closes #937
Companion PR to #946
=> feat: mirror tooling images to ghcr - part 2

pkg/patch/cmd.go, pkg/patch/patch.go, pkg/patch/patch_test.go
Adds a tag suffix to the patch command
Adds testing for the tag suffix logic
Adds extra testing to the patch command
Closes #923
=> feat: add support for custom suffix tag

integration/fixtures/tdnf-test-img/Dockerfile, integration/fixtures/test-images.json, pkg/pkgmgr/rpm.go
Adds cache cleaning commands to rpm manager
Closes #967
=> feat: invalidate tdnf cache when patching

go.mod, go.sum, pkg/buildkit/buildkit.go, pkg/patch/cmd.go, pkg/patch/patch.go
=> feat: Discover Platforms Utility

.github/workflows/golangci-lint.yml
Upgrades golangci-lint to v2.1.0
Closes #1044
=> fix: upgrade golangci-lint to v2.1.0

go.mod
=> fix: run go mod tidy

.github/workflows/build.yml, test/e2e/multiplatform-plugin/fixtures/test-images.json, test/e2e/multiplatform-plugin/main_test.go, test/e2e/multiplatform-plugin/multiplatform_plugin_test.go
Adds multiplatform e2e test for plugin system
Closes #1110
=> feat: add multiplatform e2e plugin test

README.md
=> docs: add openssf best practices badge

.github/workflows/stale.yml
Added [Close Stale Issues](https://github.com/marketplace/actions/close-stale-issues) Github Action
Closes #1175
=> feat: Add stale bot

pkg/patch/patch.go
=> feat: add riscv64 to validPlatforms

MAINTAINERS.md
@robert-cronin has made valuable contributions to copa over time
https://github.com/project-copacetic/copacetic/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Arobert-cronin
https://github.com/project-copacetic/copacetic/issues?q=sort%3Aupdated-desc%20is%3Aissue%20%20author%3Arobert-cronin
=> chore: add Robbie Cronin to maintainers

integration/singlearch/fixtures/test-images.json
=> chore: remove fluentbit eol img from tests

CODEOWNERS
=> chore: add robbie to codeowners

pkg/patch/single.go
Creates new context for descriptor lookup in `GetImageDescriptor`  so that it does not fail on local lookup and tries remote.
=> fix: create new context for local descriptor lookup

pkg/patch/patch_test.go, pkg/patch/single.go
=> feat: cli hint for renabling emulation
